### ISSUE TITLE
ERROR(s) during compilation: source code errors or compiler configuration errors!

### ISSUE THREAD

**Issue by ElwinKardux** [mhunter1/dynr#258] opened 2021-02-18 14:23 UTC
Dear admins,

I followed the Instructions for Users file, and everything seems to work. However, whenever I try to use the dynr.cook() functon (from the demo's), I get an error related to gsl: 

![image](https://user-images.githubusercontent.com/57056550/108370312-cffb9200-71fc-11eb-8f9c-9c040c1dc37c.png)

![image](https://user-images.githubusercontent.com/57056550/108370404-e7d31600-71fc-11eb-840f-c10bdc98f440.png)

I found one post with a similar question, but the solution does not fix my error: https://stackoverflow.com/questions/53735407/r-not-recognizing-gsl-library-undefined-references

Do you have any clue how to resolve this?
Thank you in advance!

**Comment by ElwinKardux** [comment] 2021-02-18 15:13
On the status page for window, similar errors are given apparently: 
https://cran.r-project.org/web/checks/check_results_dynr.html

**Comment by mhunter1** [comment] 2021-02-18 16:28
Hi Elwin,

This is a known issue and is resolved in our source code  with issue #253 .  The problem is with the current CRAN version of dynr.  It's a year old and doesn't play nicely with R 4.0.  I solved the issue back in June but haven't updated the CRAN version yet.

Can you email the maintainer from my info at https://CRAN.R-project.org/package=dynr  ?  I'll share a Dropbox link to a Windows binary that has the problem fixed.

We'll be posting the fixed version to CRAN soon!

-Mike Hunter

**Comment by mhunter1** [comment] 2021-03-02 14:33
As of CRAN version 0.1.15-95 and later, the problem is fixed.

**Closed by mhunter1** 2021-03-02 14:33 UTC
